#!/usr/bin/env ruby

require 'bundler/setup'
require 'cv/generator/pdf'
require 'thor'

class CvGenerator < Thor
  desc 'cv-generator --from YAML_FILE', 'Generate CV in PDF format'
  option :from, required: true
  def generate
    pdf = Pdf.new(options[:from])
    pdf.generate
  end
end

CvGenerator.start(ARGV.dup.unshift('generate'))
